### ISSUE TITLE
Data classes in public APIs

### ISSUE THREAD

**Issue by jayasuryat** [jayasuryat/mendable#16]
So far in this project I've avoided using `data classes` in public `APIs` as they have some unintended side-effects on `binary-compatibility`. Read more about that [here](https://jakewharton.com/public-api-challenges-in-kotlin/).

But `toString()`, `copy()` & `hashCode()` functions on `entities` is something that every consumer of this library would probably expect to exist out of the box. It's justified, they are very convenient to use and are very helpful.

If not `data classes`, writing these functions by hand is such a chore, or, even when using the IDE generated `toString()`, `copy()` & `hashCode()` functions, they are need to be maintained and kept up-to-date with changes appropriately. 

---

### So what now?

I recently came across this compiler plugin, [`Poko`](https://github.com/drewhamilton/Poko): 
> A Kotlin compiler plugin that generates equals, hashCode, and toString for plain old Kotlin objects in public APIs.

This looks like a perfect fit for the requirement, even tho it is in an experimental stage, I'm willing to try it out.

---

### TODO:

- [x] Setup Poko in version catalogue
- [x] Migrate `:metrics-file` to `Poko` & Update API changes
- [x] <del>Migrate `:scanner` to `Poko` & Update API changes</del>
- [x] Migrate `:parser` to `Poko` & Update API changes
- [x] Migrate `:mendable` to `Poko` & Update API changes
- [x] <del>Migrate `:mendable-app` to `Poko` & Update API changes</del>
