### ISSUE TITLE
`ModuleFactory` missing from the `scanFor<>Files()` methods

### ISSUE THREAD

**Issue by jayasuryat** [jayasuryat/mendable#28]
[`ModuleFactory`](https://github.com/jayasuryat/mendable/blob/a7ee7c9b129b5849fcfa55f259794281a5b7ea49/scanner/src/main/java/com/jayasuryat/mendable/scanner/ModuleFactory.kt) is missing from the [`scanFor<>Files()`](https://github.com/jayasuryat/mendable/blob/a7ee7c9b129b5849fcfa55f259794281a5b7ea49/scanner/src/main/java/com/jayasuryat/mendable/scanner/ScanerApi.kt) methods. It is currently only being used in the [`Module factory extension`](https://github.com/jayasuryat/mendable/blob/a7ee7c9b129b5849fcfa55f259794281a5b7ea49/scanner/src/main/java/com/jayasuryat/mendable/scanner/ComposeCompilerMetricsFileFactory.kt#L33).

The intension was always to expose this in the [`scanFor<>Files()`](https://github.com/jayasuryat/mendable/blob/a7ee7c9b129b5849fcfa55f259794281a5b7ea49/scanner/src/main/java/com/jayasuryat/mendable/scanner/ScanerApi.kt) methods and have [`DefaultModuleFactory`](https://github.com/jayasuryat/mendable/blob/a7ee7c9b129b5849fcfa55f259794281a5b7ea49/scanner/src/main/java/com/jayasuryat/mendable/scanner/ModuleFactory.kt#L42) as a default value. Somehow I missed this in the earlier releases.

---

### TODO
- [x] Take `ModuleFactory` as a param for all of the `scanFor<>Files()` methods with `DefaultModuleFactory` as the default value
- [x] Update tests to test if all the `scanFor<>Files()` methods are properly using the passed `ModuleFactory`
- [x] Dump and validate public `API`

This would be a backwards-source-compatible change as we are just adding a new param with default value, so all of the existing call-sites should work as is.
