### ISSUE TITLE
Update README.md to address changes made in #1, #4 & #5

### ISSUE THREAD

**Issue by jayasuryat** [jayasuryat/mendable#7]
Update `README.md` to address changes made in #1, #4 & #5. These are major changes and might change how this `tool`/`library` is consumed.

- [ ] Update `README.md` for #1
- [ ] Update `README.md` for #4
- [ ] Update `README.md` for #5

**Comment by jayasuryat** [comment]
This issue is obsolete now, and has been superseded by #19

**Comment by jayasuryat** [comment]
This issue is obsolete now, and has been superseded by https://github.com/jayasuryat/mendable/issues/19
